<a href="https://colab.research.google.com/github/Slipgrass/Loginova/blob/main/Loginova_HW8_Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Системы линейных алгебраических уравнений (СЛАУ) 

In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 5, 1]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)


[[1 2 3 2]
 [4 5 6 5]
 [7 8 9 1]]


(2, 3)

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[0, 0, 0]])
print(np.linalg.det(A))
C = np.concatenate((A,B.T), axis=1)
print(C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)


0.0
[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]


(2, 2)

In [32]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[4, -2, -8]])
print(np.linalg.det(A))
C = np.concatenate((A,B.T), axis=1)
print(C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

0.0
[[ 1  2  3  4]
 [ 4  5  6 -2]
 [ 7  8  9 -8]]


(2, 2)

In [33]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[3, -3, -9]])
print(np.linalg.det(A))
C = np.concatenate((A,B.T), axis=1)
print(C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

0.0
[[ 1  2  3  3]
 [ 4  5  6 -3]
 [ 7  8  9 -9]]


(2, 2)