<a href="https://colab.research.google.com/github/Slipgrass/Loginova/blob/main/Loginova_HW6_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float) #создаем матрицу А
B = np.array([12, 2, 1])  #Создаем вектор В
np.linalg.solve(A, B) # получаем решение в виде вектора неизвестных

array([-9.2       ,  0.9       ,  6.46666667])

In [ ]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float) # создаем матрицу А
B = np.array([12, 2, 1])  #Создаем вектор В
A1 = np.linalg.inv(A) # создаём обратную матрицу А1
print(A1)
print("det =", np.linalg.det(A)) # определяем детерминант матрицы А
np.dot(A1, B) # перемножаем матрицу А1 и вектор В, находим вектор Х. 

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
det = 59.999999999999986


array([-9.2       ,  0.9       ,  6.46666667])