<a href="https://colab.research.google.com/github/Slipgrass/Loginova/blob/main/Loginova_HW8_Task6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание 6. Найти одно из псевдорешений вырожденной системы.
Найти нормальное решение.

In [18]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [10]:
print(np.dot(Q, R))
print(np.dot(np.transpose(Q), Q))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.00000000e+00 -2.48218629e-16 -2.62094065e-17]
 [-2.48218629e-16  1.00000000e+00  2.82872043e-17]
 [-2.62094065e-17  2.82872043e-17  1.00000000e+00]]


In [12]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [13]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  3.55271368e-15])

In [14]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 3.92767275e-15])

In [15]:
X = np.append(X1, 0)
print(X)
np.linalg.norm(X)

[1.50000000e+00 3.92767275e-15 0.00000000e+00]


1.499999999999996

In [16]:
np.linalg.norm(np.dot(A, X) - B)

1.224744871391589

In [21]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
np.linalg.lstsq(A, B, rcond=None) #нашли псевдорешение системы уравнений

(array([ 1.25,  0.5 , -0.25]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))

In [22]:
X = np.array([ 1.25,  0.5 , -0.25])
np.linalg.norm(X), np.linalg.norm(np.dot(A, X) - B)

(1.3693063937629153, 1.224744871391589)